### PR TITLE
Events and state bindings

### PR DESCRIPTION
**Pull request by cyonii**
In this milestone I have bind my `App` component to a state, and events to their respective handlers, implementing the calculator logic and operations

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
## Hello @cyonii,
**You have done a commendable job on this milestone**

However, there are some changes to be made before you can move forward

- [ ] Kindly check the below errors displayed in the browser console and fix them.
Screenshot from 2021-07-16 12-08-56
- [ ] Try deleting the default files that come with react in the public folder e.g `manifest`, `favicon`, and `robots` to see if this fixes the errors


**Please make the above change and ask for another review**

Feel free to leave a comment while mentioning me and I will be happy to reply.
### Happy Coding
_Slack: Oloo Moses_

**Comment by cyonii** [comment]
Hello @oloomoses, thanks for the review.
I have deleted and cloned this repository again, and I cannot see any error outputs in the console.
Could you clarify what error is being displayed, and at what point and actions.

Thank you.

**Review by Elbie-em — APPROVED** [review]
## STATUS: APPROVED ✅ 

Congratulations @cyonii for doing an awesome job, you can move forward.

*All the best and keep up the good work* 💪 

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

**Comment by cyonii** [comment]
Thank you @Elbie-em

**Pull request merged**
